export const rankingPhrases: string[] = [
  "World Best",
  "Best",
  "#1",
  "Top",
  "Top Rated",
  "Most Popular",
  "Highly Rated",
  "Top Pick",
  "Top Choice",
  "Top Ranked",
  "Ranked #1",
  "Top 10",
  "Top 5",
  "Top 3",
  "1st Place",
  "2nd Place",
  "3rd Place",
  "Editor's Choice",
  "Top Recommendation",
  "Customer Favorite",
  "Fan Favorite",
  "Ultimate",
  "Greatest",
  "Finest",
  "Elite",
  "Outstanding",
  "Superb",
  "Unbeatable",
  "Epic",
  "Legendary",
  "Premium",
  "Must Try",
  "Top Of The Line",
  "Number One",
  "Top Class",
  "Champion",
];
